### ISSUE TITLE
Fix up FutureEvents component

### ISSUE THREAD

**Issue by danielcodes** [CUNYTech/JobQuest#21]
Get rid of all the materialize classes and use material-ui components instead

**Comment by danielcodes** [comment]
Also, component does not render when the data prop is not passed, fix with:
```Javascript
{this.props.data ? this.props.data.map(function(events){
   return (
      <Events data={events} />
      );
   })
   : null}
```

**Comment by EAlman21** [comment]
Gotcha. Also we need to add a Schema for the Calendar/Events
