### ISSUE TITLE
Fix up UI for individual post page

### ISSUE THREAD

**Issue by danielcodes** [CUNYTech/JobQuest#34]
Also, the link on the title has a redundant `/thread` in the front.

**Comment by EAlman21** [comment]
you should check joseph's branch. the way it is set up so far looks good.

**Comment by danielcodes** [comment]
Passing a long description for the post completely wrecks the UI. `div` containing the description should be set a certain size and grow accordingly.

![long_desc](https://cloud.githubusercontent.com/assets/4009751/24592502/de93d22a-17e5-11e7-9345-53196705aa55.png)

**Comment by danielcodes** [comment]
Also, If title is too long, trim it down to couple of words.
